/FR_ROS_API_node:
  ros__parameters:
    AO_block: 1 #模拟输出是否阻塞, 0-阻塞，1-非阻塞
    DO_block: 1 #数字输出是否阻塞，0-阻塞，1-非阻塞
    DO_smooth: 0 #数字输出平滑，0-不平滑，1-平滑
    JOG_acc: 40 #JOG指令加速度百分比
    JOG_maxdis: 5 #JOG指令单次点动最大角度或者距离，单位是度或者mm
    MoveC_blendR: 500.0 #MOVEC指令的平滑半径  [-1.0]-运动到位(阻塞)，[0~1000.0]-平滑半径(非阻塞)，单位mm
    MoveJLC_acc: 0.0 #MOVEJ MOVEL MOVEC指令 加速度百分比参数，暂不开放
    MoveJLC_eaxis1: 0.0 #MOVEJ MOVEL MOVEC指令  扩展轴1位置参数
    MoveJLC_eaxis2: 0.0 #MOVEJ MOVEL MOVEC指令 扩展轴2位置参数
    MoveJLC_eaxis3: 0.0 #MOVEJ MOVEL MOVEC指令 扩展轴3位置参数
    MoveJLC_eaxis4: 0.0 #MOVEJ MOVEL MOVEC指令 扩展轴4位置参数
    MoveJLC_offset_flag: 0 # MOVEJ MOVEL MOVEC指令 轨迹偏移参数 0-不偏移，1-基坐标系/工件坐标系下偏移，2-工具坐标系下偏移
    MoveJLC_offset_pos_rx: 0.0 #MOVEJ MOVEL MOVEC指令 轨迹偏移参数 rx角度偏移值
    MoveJLC_offset_pos_ry: 0.0 #MOVEJ MOVEL MOVEC指令 轨迹偏移参数 ry角度偏移值
    MoveJLC_offset_pos_rz: 0.0 #MOVEJ MOVEL MOVEC指令 轨迹偏移参数 rz角度偏移值
    MoveJLC_offset_pos_x: 0.0 #MOVEJ MOVEL MOVEC指令 轨迹偏移参数 x偏移值
    MoveJLC_offset_pos_y: 0.0 #MOVEJ MOVEL MOVEC指令 轨迹偏移参数 y偏移值
    MoveJLC_offset_pos_z: 0.0 #MOVEJ MOVEL MOVEC指令 轨迹偏移参数 z偏移值
    MoveJLC_ovl: 100.0 #MOVEJ MOVEL MOVEC指令 速度缩放因子参数 范围0-100
    MoveJLC_tool: 0 #MOVEJ MOVEL MOVEC指令 工具坐标系标号
    MoveJLC_user: 0 #MOVEJ MOVEL MOVEC指令 工件坐标系标号
    MoveJ_blendT: 500.0 #MOVEJ指令 平滑时间参数  [-1.0]-运动到位(阻塞)，[0~500.0]-平滑时间(非阻塞)，单位ms
    MoveL_blendR: 500.0 #MOVEL指令 平滑时间参数  [-1.0]-运动到位(阻塞)，[0~1000.0]-平滑半径(非阻塞)，单位mm
    MoveL_search: 0.0 #MOVEL指令 焊丝寻位参数  0-不焊丝寻位，1-焊丝寻位
    NewSpline_blendR: 10.0 #笛卡尔样条指令 平滑半径参数 单位mm
    Spline_acc: 0.0 #关节空间样条指令 加速度百分比
    Spline_ovl: 100.0 #关节空间样条指令 速度缩放因子 范围0-100
    Spline_tool: 1 #关节空间样条指令 工具坐标标号
    Spline_user: 0 #关节空间样条指令 工件坐标标号
    collision_config: 1 #碰撞配置文件设置, 0-更新配置文件 1-不更新配置文件
    collision_mode: 0 #碰撞等级模式,0-等级， 1-百分比 范围0-1
    gripper_block: 1 #movegripper指令中阻塞配置参数 0-阻塞，1-非阻塞
    gripper_force: 50 #movegripper指令中力矩百分比配置参数 范围0-100
    gripper_vel: 50 #movegripper指令中速度百分比配置参数  范围0-100
    gripper_maxtime: 30000 #movegripper指令中最大等待时间配置参数 范围0-30000 单位ms 
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    toolcoord_install: 0 #SetToolCoord SetToolList指令中 工具安装位置参数 0-机器人末端，1-机器人外部
    toolcoord_type: 0 #SetToolCoord SetToolList指令中 坐标系类型参数 0-工具坐标系，1-传感器坐标系
    ServoJT_timeinterval: 0.008 #ServoJT指令 指令周期参数 默认8ms
    use_sim_time: false

