uint8 model #标定的模式和其它功能
string base_param #基础参数 像元尺寸,标定板类型,标定板尺寸,标定板的间距
float64 x_step #x_方向的步长
float64 y_step #y_方向的步长
float64 angle_step #角度步长
float64[] input_poses #输入的位姿
---
bool cmd_result #命令执行结果
string error_msg #错误信息
float64[] output_poses #输出位姿
